<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "annuaire_tars"
 *
 * Auto generated by Extension Builder 2017-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Annuaire_TARS',
	'description' => 'Tiphaine Girardot
Romain Durade
Alexandre Duviviers
Sylvain Metayer

0.1.1 : Add Properties
0.1.2 : Add Relations
0.1.3 : Add Actions
0.1.4 : Add FrontEnd Plugins',
	'category' => 'plugin',
	'author' => 'Tiphaine GIRARDOT, Romain DURADE, Alexandre DUVIVIERS, Sylvain METAYER',
	'author_email' => 'tiphaine.girardot@etu.u-bordeaux.fr, romain.durade@etu.u-bordeaux.fr, alexandre.duviviers@etu.u-bordeaux.fr, sylvain.metayer@etu.u-bordeaux.fr',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.4',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);